project:
  type: website
  output-dir: _site
  resources:
    - papers/**
    - reynolds_cv.pdf
    - nicholas_reynolds_headshot.jpg

website:
  title: "Nicholas Reynolds"
  navbar:
    left:
      - href: index.qmd#top
        text: Home
      - href: index.qmd#news
        text: News
      - href: index.qmd#research
        text: Research
      - href: index.qmd#teaching
        text: Teaching
      - href: index.qmd#contact
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-newwindow: true
