project:
  type: website
  output-dir: _site

website:
  title: "Nicholas Reynolds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: false
