project:
  type: website
  output-dir: _site
  resources:
    - papers/**
    - reynolds_cv.pdf

website:
  title: "Nicholas Reynolds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
      - href: design-options.qmd
        text: Design Options

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: false
